spring.application.name=user-service
server.port=8081

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

# Actuator
management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=User Service
info.app.description=Handles user registration, login, and JWT authentication
info.app.version=1.0.0

# JWT Configuration
jwt.secret=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnYW1haWwuY29tIiwiaWF0IjoxNzUzNjMxMTg0LCJleHAiOjE3NTM3MTc1ODR9.zJkX9c3fQ6d3sJ8n5P2lq8j6h0k6G5w0H1Z4W2L7t8A
jwt.expiration=86400000
