spring.application.name=claim-service
server.port=8084

# H2 Database
spring.datasource.url=jdbc:h2:mem:claimdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

# Actuator
management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.health.show-details=always
info.app.name=Claim Service
info.app.description=Manages ownership claims
info.app.version=1.0.0

# JWT
jwt.secret=CampusLostAndFoundPortalSecretKeyForJWTAuthenticationMustBeLongEnough2024
